images:
  -
    image: 
      - shyim/shopware-classic-nginx
      - docker.pkg.github.com/shyim/shopware-docker/nginx-sw5
    buildTags: [ 'nginx' ]
    dockerFile: nginx/Dockerfile
    context: nginx 
    templates:
      nginx/Dockerfile.twig: nginx/Dockerfile
      nginx/10-classic.conf: nginx/rootfs/etc/nginx/sites-enabled/www.conf
    tags:
      php56:
        phpVersion: '5.6'
        phpVersionNumeric: 56
      php70:
        phpVersion: '7.0'
        phpVersionNumeric: 70
      php71:
        phpVersion: '7.1'
        phpVersionNumeric: 71
      php72:
        phpVersion: '7.2'
        phpVersionNumeric: 72
      php73:
        phpVersion: '7.3'
        phpVersionNumeric: 73
      php74:
        phpVersion: '7.4'
        phpVersionNumeric: 74
  -
    image: 
      - shyim/shopware-platform-nginx
      - docker.pkg.github.com/shyim/shopware-docker/nginx-sw6
    buildTags: [ 'nginx' ]
    dockerFile: nginx/Dockerfile
    context: nginx 
    templates:
      nginx/Dockerfile.twig: nginx/Dockerfile
      nginx/10-platform.conf: nginx/rootfs/etc/nginx/sites-enabled/www.conf
    tags:
      php72:
        phpVersion: '7.2'
        phpVersionNumeric: 72
      php73:
        phpVersion: '7.3'
        phpVersionNumeric: 73
      php74:
        phpVersion: '7.4'
        phpVersionNumeric: 74