pool:
  vmImage: 'ubuntu-latest'
  
trigger:
- master

strategy:
  matrix:
    cli:
      MODULE: "cli"
    clixdebug:
      MODULE: "cli-xdebug"
    nginx:
      MODULE: "nginx"
    blackfire:
      MODULE: "blackfire"
    production:
      MODULE: "production"
    xdebug:
      MODULE: "xdebug"
    mysql:
      MODULE: "mysql"

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

- script: |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    cd images/
    npm install
    node build.js build ${MODULE}
    node build.js push ${MODULE}
  displayName: 'Build image and push'