pool:
  vmImage: 'ubuntu-latest'
  
trigger:
- master

strategy:
  matrix:
    cli:
      MODULE: "cli"
    clixdebug:
      MODULE: "cli-xdebug"
    nginx:
      MODULE: "nginx"
    blackfire:
      MODULE: "blackfire"
    production:
      MODULE: "production"
    xdebug:
      MODULE: "xdebug"
    mysql:
      MODULE: "mysql"

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

- script: |
    cd images/
    npm install
    node build.js build ${MODULE}
    node build.js push ${MODULE}
  displayName: 'Build image and push'

- task: Docker@2
  condition: eq(variables['MODULE'], 'mysql')
  displayName: 'Push MySQL Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-mysql'
    command: 'push'
    tags: |
      57
      8

- task: Docker@2
  condition: eq(variables['MODULE'], 'xdebug')
  displayName: 'Push XDebug Shopware 6 Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-platform-nginx'
    command: 'push'
    tags: |
      php74-xdebug
      php73-xdebug
      php72-xdebug

- task: Docker@2
  condition: eq(variables['MODULE'], 'xdebug')
  displayName: 'Push XDebug Shopware 5 Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-classic-nginx'
    command: 'push'
    tags: |
      php74-xdebug
      php73-xdebug
      php72-xdebug
      php71-xdebug
      php70-xdebug
      php56-xdebug

- task: Docker@2
  condition: eq(variables['MODULE'], 'nginx')
  displayName: 'Push Nginx Shopware 6 Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-platform-nginx'
    command: 'push'
    tags: |
      php72
      php73
      php74

- task: Docker@2
  condition: eq(variables['MODULE'], 'nginx')
  displayName: 'Push Nginx Shopware 5 Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-classic-nginx'
    command: 'push'
    tags: |
      php56
      php70
      php71
      php72
      php73
      php74

- task: Docker@2
  condition: eq(variables['MODULE'], 'cli')
  displayName: 'Push Cli Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-cli'
    command: 'push'
    tags: |
      php56
      php70
      php71
      php72
      php73
      php74

- task: Docker@2
  condition: eq(variables['MODULE'], 'cli-xdebug')
  displayName: 'Push Cli-Xdebug Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-cli'
    command: 'push'
    tags: |
      php56-xdebug
      php70-xdebug
      php71-xdebug
      php72-xdebug
      php73-xdebug
      php74-xdebug

- task: Docker@2
  condition: eq(variables['MODULE'], 'production')
  displayName: 'Push Production SW5'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-classic-nginx-production'
    command: 'push'
    tags: |
      php73
      php74

  - task: Docker@2
  condition: eq(variables['MODULE'], 'production')
  displayName: 'Push Production SW6'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-platform-nginx-production'
    command: 'push'
    tags: |
      php73
      php74