name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        module: ['cli', 'cli-xdebug', 'nginx', 'blackfire', 'production', 'xdebug', 'mysql', 'apache']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '12.x'

    - name: Build image and push
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "shyim" --password-stdin
        cd images/
        npm install
        node build.js build ${{ matrix.module }}
        node build.js push ${{ matrix.module }}
